// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Valisys_Production.Data;

#nullable disable

namespace Valisys_Production.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251202205051_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Valisys_Production.Models.Almoxarifado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Contato")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Almoxarifados");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000009"),
                            Ativo = true,
                            Contato = "(67) 99999-9999",
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Almoxarifado principal",
                            Email = "almoxarifado@empresa.com",
                            Localizacao = "Galpão 1",
                            Nome = "Almoxarifado Geral",
                            Responsavel = "Sistema"
                        });
                });

            modelBuilder.Entity("Valisys_Production.Models.CategoriaProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("CategoriasProduto");
                });

            modelBuilder.Entity("Valisys_Production.Models.FaseProducao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("TempoPadraoDias")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FasesProducao");
                });

            modelBuilder.Entity("Valisys_Production.Models.FichaTecnica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoFicha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("FichasTecnicas");
                });

            modelBuilder.Entity("Valisys_Production.Models.FichaTecnicaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FichaTecnicaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PerdaPercentual")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProdutoComponenteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FichaTecnicaId");

                    b.HasIndex("ProdutoComponenteId");

                    b.ToTable("FichaTecnicaItens");
                });

            modelBuilder.Entity("Valisys_Production.Models.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("Valisys_Production.Models.LogSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsSistema");
                });

            modelBuilder.Entity("Valisys_Production.Models.Lote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlmoxarifadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoLote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<int>("statusLote")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlmoxarifadoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("Valisys_Production.Models.Movimentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlmoxarifadoDestinoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlmoxarifadoOrigemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrdemDeProducaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlmoxarifadoDestinoId");

                    b.HasIndex("AlmoxarifadoOrigemId");

                    b.HasIndex("OrdemDeProducaoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("Valisys_Production.Models.OrdemDeProducao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlmoxarifadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoOrdem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FaseAtualId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RoteiroProducaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SolicitacaoProducaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TipoOrdemDeProducaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlmoxarifadoId");

                    b.HasIndex("FaseAtualId");

                    b.HasIndex("LoteId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("RoteiroProducaoId");

                    b.HasIndex("SolicitacaoProducaoId")
                        .IsUnique();

                    b.HasIndex("TipoOrdemDeProducaoId");

                    b.ToTable("OrdensDeProducao");
                });

            modelBuilder.Entity("Valisys_Production.Models.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<string>>("Acessos")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Perfis");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000001"),
                            Acessos = new List<string>(),
                            Ativo = true,
                            Nome = "Administrador"
                        });
                });

            modelBuilder.Entity("Valisys_Production.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CategoriaProdutoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Classificacao")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoInternoProduto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("ControlarPorLote")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UnidadeMedidaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaProdutoId");

                    b.HasIndex("CodigoInternoProduto")
                        .IsUnique();

                    b.HasIndex("UnidadeMedidaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Valisys_Production.Models.RoteiroProducao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("RoteirosProducao");
                });

            modelBuilder.Entity("Valisys_Production.Models.RoteiroProducaoEtapa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FaseProducaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Instrucoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoteiroProducaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("TempoDias")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FaseProducaoId");

                    b.HasIndex("RoteiroProducaoId");

                    b.ToTable("RoteiroProducaoEtapas");
                });

            modelBuilder.Entity("Valisys_Production.Models.SolicitacaoProducao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoSolicitacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EncarregadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TipoOrdemDeProducaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioAprovacaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EncarregadoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("TipoOrdemDeProducaoId");

                    b.HasIndex("UsuarioAprovacaoId");

                    b.ToTable("SolicitacoesProducao");
                });

            modelBuilder.Entity("Valisys_Production.Models.SolicitacaoProducaoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<Guid>("SolicitacaoProducaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("SolicitacaoProducaoId");

                    b.ToTable("SolicitacaoProducaoItens");
                });

            modelBuilder.Entity("Valisys_Production.Models.TipoOrdemDeProducao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposDeOrdemDeProducao");
                });

            modelBuilder.Entity("Valisys_Production.Models.UnidadeMedida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<bool>("EhUnidadeBase")
                        .HasColumnType("boolean");

                    b.Property<decimal>("FatorConversao")
                        .HasColumnType("numeric");

                    b.Property<int>("Grandeza")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("UnidadesMedida");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000002"),
                            Ativo = true,
                            EhUnidadeBase = true,
                            FatorConversao = 1m,
                            Grandeza = 0,
                            Nome = "Unidade",
                            Sigla = "UN"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000020"),
                            Ativo = true,
                            EhUnidadeBase = false,
                            FatorConversao = 1m,
                            Grandeza = 0,
                            Nome = "Peça",
                            Sigla = "PC"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000021"),
                            Ativo = true,
                            EhUnidadeBase = false,
                            FatorConversao = 1m,
                            Grandeza = 0,
                            Nome = "Caixa",
                            Sigla = "CX"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000022"),
                            Ativo = true,
                            EhUnidadeBase = false,
                            FatorConversao = 1m,
                            Grandeza = 0,
                            Nome = "Kit",
                            Sigla = "KIT"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000023"),
                            Ativo = true,
                            EhUnidadeBase = false,
                            FatorConversao = 12m,
                            Grandeza = 0,
                            Nome = "Dúzia",
                            Sigla = "DZ"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000024"),
                            Ativo = true,
                            EhUnidadeBase = false,
                            FatorConversao = 1000m,
                            Grandeza = 0,
                            Nome = "Milheiro",
                            Sigla = "MIL"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000003"),
                            Ativo = true,
                            EhUnidadeBase = true,
                            FatorConversao = 1m,
                            Grandeza = 1,
                            Nome = "Kilograma",
                            Sigla = "KG"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000099"),
                            Ativo = true,
                            EhUnidadeBase = false,
                            FatorConversao = 0.001m,
                            Grandeza = 1,
                            Nome = "Grama",
                            Sigla = "G"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000031"),
                            Ativo = true,
                            EhUnidadeBase = false,
                            FatorConversao = 0.000001m,
                            Grandeza = 1,
                            Nome = "Miligrama",
                            Sigla = "MG"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000032"),
                            Ativo = true,
                            EhUnidadeBase = false,
                            FatorConversao = 1000m,
                            Grandeza = 1,
                            Nome = "Tonelada",
                            Sigla = "TON"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000012"),
                            Ativo = true,
                            EhUnidadeBase = true,
                            FatorConversao = 1m,
                            Grandeza = 2,
                            Nome = "Metro",
                            Sigla = "M"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000040"),
                            Ativo = true,
                            EhUnidadeBase = false,
                            FatorConversao = 0.01m,
                            Grandeza = 2,
                            Nome = "Centímetro",
                            Sigla = "CM"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000041"),
                            Ativo = true,
                            EhUnidadeBase = false,
                            FatorConversao = 0.001m,
                            Grandeza = 2,
                            Nome = "Milímetro",
                            Sigla = "MM"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000042"),
                            Ativo = true,
                            EhUnidadeBase = false,
                            FatorConversao = 1000m,
                            Grandeza = 2,
                            Nome = "Quilômetro",
                            Sigla = "KM"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000050"),
                            Ativo = true,
                            EhUnidadeBase = true,
                            FatorConversao = 1m,
                            Grandeza = 3,
                            Nome = "Litro",
                            Sigla = "L"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000051"),
                            Ativo = true,
                            EhUnidadeBase = false,
                            FatorConversao = 0.001m,
                            Grandeza = 3,
                            Nome = "Mililitro",
                            Sigla = "ML"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000052"),
                            Ativo = true,
                            EhUnidadeBase = false,
                            FatorConversao = 1000m,
                            Grandeza = 3,
                            Nome = "Metro Cúbico",
                            Sigla = "M3"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000060"),
                            Ativo = true,
                            EhUnidadeBase = true,
                            FatorConversao = 1m,
                            Grandeza = 5,
                            Nome = "Metro Quadrado",
                            Sigla = "M2"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000061"),
                            Ativo = true,
                            EhUnidadeBase = false,
                            FatorConversao = 0.0001m,
                            Grandeza = 5,
                            Nome = "Centímetro Quadrado",
                            Sigla = "CM2"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000070"),
                            Ativo = true,
                            EhUnidadeBase = true,
                            FatorConversao = 1m,
                            Grandeza = 4,
                            Nome = "Hora",
                            Sigla = "H"
                        },
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000071"),
                            Ativo = true,
                            EhUnidadeBase = false,
                            FatorConversao = 0.0166667m,
                            Grandeza = 4,
                            Nome = "Minuto",
                            Sigla = "MIN"
                        });
                });

            modelBuilder.Entity("Valisys_Production.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0de0000-0000-0000-0000-000000000000"),
                            Ativo = true,
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@valisys.com",
                            Nome = "Administrador Master",
                            PerfilId = new Guid("c0de0000-0000-0000-0000-000000000001"),
                            SenhaHash = "$2a$12$ceV2TtMQV.UXqYGXoyMt.eV9s2YcTh0SVykcjMPxxDxjci9hoYzeG"
                        });
                });

            modelBuilder.Entity("Valisys_Production.Models.FichaTecnica", b =>
                {
                    b.HasOne("Valisys_Production.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Valisys_Production.Models.FichaTecnicaItem", b =>
                {
                    b.HasOne("Valisys_Production.Models.FichaTecnica", "FichaTecnica")
                        .WithMany("Itens")
                        .HasForeignKey("FichaTecnicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Valisys_Production.Models.Produto", "ProdutoComponente")
                        .WithMany()
                        .HasForeignKey("ProdutoComponenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FichaTecnica");

                    b.Navigation("ProdutoComponente");
                });

            modelBuilder.Entity("Valisys_Production.Models.LogSistema", b =>
                {
                    b.HasOne("Valisys_Production.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Valisys_Production.Models.Lote", b =>
                {
                    b.HasOne("Valisys_Production.Models.Almoxarifado", "Almoxarifado")
                        .WithMany()
                        .HasForeignKey("AlmoxarifadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Valisys_Production.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almoxarifado");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Valisys_Production.Models.Movimentacao", b =>
                {
                    b.HasOne("Valisys_Production.Models.Almoxarifado", "AlmoxarifadoDestino")
                        .WithMany()
                        .HasForeignKey("AlmoxarifadoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Valisys_Production.Models.Almoxarifado", "AlmoxarifadoOrigem")
                        .WithMany()
                        .HasForeignKey("AlmoxarifadoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Valisys_Production.Models.OrdemDeProducao", "OrdemDeProducao")
                        .WithMany()
                        .HasForeignKey("OrdemDeProducaoId");

                    b.HasOne("Valisys_Production.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Valisys_Production.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlmoxarifadoDestino");

                    b.Navigation("AlmoxarifadoOrigem");

                    b.Navigation("OrdemDeProducao");

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Valisys_Production.Models.OrdemDeProducao", b =>
                {
                    b.HasOne("Valisys_Production.Models.Almoxarifado", "Almoxarifado")
                        .WithMany()
                        .HasForeignKey("AlmoxarifadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Valisys_Production.Models.FaseProducao", "FaseAtual")
                        .WithMany("OrdensDeProducao")
                        .HasForeignKey("FaseAtualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Valisys_Production.Models.Lote", "Lote")
                        .WithMany("OrdensDeProducao")
                        .HasForeignKey("LoteId");

                    b.HasOne("Valisys_Production.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Valisys_Production.Models.RoteiroProducao", "RoteiroProducao")
                        .WithMany()
                        .HasForeignKey("RoteiroProducaoId");

                    b.HasOne("Valisys_Production.Models.SolicitacaoProducao", "SolicitacaoProducao")
                        .WithOne("OrdemDeProducao")
                        .HasForeignKey("Valisys_Production.Models.OrdemDeProducao", "SolicitacaoProducaoId");

                    b.HasOne("Valisys_Production.Models.TipoOrdemDeProducao", "TipoOrdemDeProducao")
                        .WithMany("OrdensDeProducao")
                        .HasForeignKey("TipoOrdemDeProducaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almoxarifado");

                    b.Navigation("FaseAtual");

                    b.Navigation("Lote");

                    b.Navigation("Produto");

                    b.Navigation("RoteiroProducao");

                    b.Navigation("SolicitacaoProducao");

                    b.Navigation("TipoOrdemDeProducao");
                });

            modelBuilder.Entity("Valisys_Production.Models.Produto", b =>
                {
                    b.HasOne("Valisys_Production.Models.CategoriaProduto", "CategoriaProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Valisys_Production.Models.UnidadeMedida", "UnidadeMedida")
                        .WithMany("Produtos")
                        .HasForeignKey("UnidadeMedidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaProduto");

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("Valisys_Production.Models.RoteiroProducao", b =>
                {
                    b.HasOne("Valisys_Production.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Valisys_Production.Models.RoteiroProducaoEtapa", b =>
                {
                    b.HasOne("Valisys_Production.Models.FaseProducao", "FaseProducao")
                        .WithMany()
                        .HasForeignKey("FaseProducaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Valisys_Production.Models.RoteiroProducao", "RoteiroProducao")
                        .WithMany("Etapas")
                        .HasForeignKey("RoteiroProducaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaseProducao");

                    b.Navigation("RoteiroProducao");
                });

            modelBuilder.Entity("Valisys_Production.Models.SolicitacaoProducao", b =>
                {
                    b.HasOne("Valisys_Production.Models.Usuario", "Encarregado")
                        .WithMany()
                        .HasForeignKey("EncarregadoId");

                    b.HasOne("Valisys_Production.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Valisys_Production.Models.TipoOrdemDeProducao", "TipoOrdemDeProducao")
                        .WithMany()
                        .HasForeignKey("TipoOrdemDeProducaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Valisys_Production.Models.Usuario", "UsuarioAprovacao")
                        .WithMany()
                        .HasForeignKey("UsuarioAprovacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encarregado");

                    b.Navigation("Produto");

                    b.Navigation("TipoOrdemDeProducao");

                    b.Navigation("UsuarioAprovacao");
                });

            modelBuilder.Entity("Valisys_Production.Models.SolicitacaoProducaoItem", b =>
                {
                    b.HasOne("Valisys_Production.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Valisys_Production.Models.SolicitacaoProducao", "SolicitacaoProducao")
                        .WithMany("Itens")
                        .HasForeignKey("SolicitacaoProducaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("SolicitacaoProducao");
                });

            modelBuilder.Entity("Valisys_Production.Models.Usuario", b =>
                {
                    b.HasOne("Valisys_Production.Models.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Valisys_Production.Models.CategoriaProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Valisys_Production.Models.FaseProducao", b =>
                {
                    b.Navigation("OrdensDeProducao");
                });

            modelBuilder.Entity("Valisys_Production.Models.FichaTecnica", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Valisys_Production.Models.Lote", b =>
                {
                    b.Navigation("OrdensDeProducao");
                });

            modelBuilder.Entity("Valisys_Production.Models.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Valisys_Production.Models.RoteiroProducao", b =>
                {
                    b.Navigation("Etapas");
                });

            modelBuilder.Entity("Valisys_Production.Models.SolicitacaoProducao", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("OrdemDeProducao")
                        .IsRequired();
                });

            modelBuilder.Entity("Valisys_Production.Models.TipoOrdemDeProducao", b =>
                {
                    b.Navigation("OrdensDeProducao");
                });

            modelBuilder.Entity("Valisys_Production.Models.UnidadeMedida", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
